### ISSUE TITLE
[Feature request] Create classes directly in `integrations_path` directory

### ISSUE THREAD

**Issue by binaryfire** [saloonphp/laravel-plugin#47]
`integrations_path` is very useful for modular and DDD architectures. It'd be great if the Saloon commands could create their new classes directly in that directory. Perhaps an optional config setting? The ability to set a custom base namespace would be great too.

**Comment by JonPurvis** [comment]
Hey @binaryfire,

This was actually discussed quite recently in https://github.com/saloonphp/laravel-plugin/pull/46 (where `integrations_path` was added initially). 

I was planning to look into this soon, but if you fancy taking it on, be my guest! 😄

**Comment by Sammyjo20** [comment]
Hey @JonPurvis it seems that Saloon v3 launched successfully and the Laravel plugin is pretty stable! I'd be happy to accept a PR (or do it myself) to remove Laravel 9 support so you can install prompts and carry on with your command?

**Comment by JonPurvis** [comment]
Hey @Sammyjo20 👋 

I'd be happy to look into this sometime over the weekend! I'm still very much in favour of us being able to use the power of Prompts to make this plugin even more awesome! 💪

**Comment by Sammyjo20** [comment]
Awesome! This weekend I'm going to a bunch of open source stuff so I can help if needed.

**Comment by Sammyjo20** [comment]
Hey @JonPurvis this came up for me today - I was wondering if you still wanted to contribute this? No worries if not as I can do it too 🙌

**Comment by JonPurvis** [comment]
Hey @Sammyjo20 

I just realised I said I was going to look into this back in November 😆 my bad!

Happy to still look into it, work has been pretty hectic recently so my Open Source work has decreased slightly. That said, I'm still happy to look into this one evening this week, if that works for you?

**Comment by Sammyjo20** [comment]
That'll be amazing, thank you <3 Please do shout if you want me to help!

**Comment by JonPurvis** [comment]
Had some time to work on this yesterday and I've just created a PR with the solution! 

https://github.com/saloonphp/laravel-plugin/pull/56
