### ISSUE TITLE
Saloon:list command doesn't handle directories

### ISSUE THREAD

**Issue by Cbrad24** [saloonphp/laravel-plugin#53]
If you have a more complex directory structure the `php artisan saloon:list` command does not properly recurse subdirectories.

If you have subfolders inside the Requests folder they are treated as files, and `file_get_contents()` throws a `Is a directory` error, as well as any Request classes inside the subdirectory not getting shown.

![image](https://github.com/saloonphp/laravel-plugin/assets/2669153/95325b15-2d24-4343-a8ad-79697fbbd6c7)

**Comment by Sammyjo20** [comment]
Hey @Cbrad24 thank you for raising this - I'll take a look and see what I can do! 

@JonPurvis Hope you are well mate, I hope you don't mind me mentioning you - do you reckon we should use something like symfony/finder for listing files recursively, or perhaps we should try to detect directories?

I'm happy to make the changes but since you wrote this I wanted a second opinion.

**Comment by JonPurvis** [comment]
Hey @Sammyjo20 

Don't worry about the direct mention! It's all good 😄 

Absolutely, I suppose there's endless ways that applications could have files structured and I only really tested a couple of them. I don't have much experience with `symfony/finder`, but having looked over the documentation, I think it would suit what's needed here.

👍 from me!

**Comment by JonPurvis** [comment]
Hey @Sammyjo20 

I decided to take a stab at this one over the weekend and came up with https://github.com/saloonphp/laravel-plugin/pull/58

There's a few more improvements I'd like to make to that command, but I've made a list of them and will hopefully get some time in the next couple of months to action them. That PR though, fixes this issue, in that if you have your Requests within subfolders, `saloon:list` will still pick them up!

**Comment by Sammyjo20** [comment]
Awesome work man, I've merged it and I will include it in the next release (I want to merge your other one and a small PR of mine I'm working on)

**Comment by JonPurvis** [comment]
Great, thanks for a speedy merge! 🚤
